export const EFFECTIVE = {
  ALL: 'ALL',
  CURRENT: 'CURRENT',
  FUTURE: 'FUTURE',
};

export const PRODUCT_CATEGORY = {
  BUSINESS_LOANS: 'BUSINESS_LOANS',
  CRED_AND_CHRG_CARDS: 'CRED_AND_CHRG_CARDS',
  LEASES: 'LEASES',
  MARGIN_LOANS: 'MARGIN_LOANS',
  OVERDRAFTS: 'OVERDRAFTS',
  PERS_LOANS: 'PERS_LOANS',
  REGULATED_TRUST_ACCOUNTS: 'REGULATED_TRUST_ACCOUNTS',
  RESIDENTIAL_MORTGAGES: 'RESIDENTIAL_MORTGAGES',
  TERM_DEPOSITS: 'TERM_DEPOSITS',
  TRADE_FINANCE: 'TRADE_FINANCE',
  TRANS_AND_SAVINGS_ACCOUNTS: 'TRANS_AND_SAVINGS_ACCOUNTS',
  TRAVEL_CARDS: 'TRAVEL_CARDS',
};

export const PRODUCT_CATEGORY_ARRAY = [
  'BUSINESS_LOANS',
  'CRED_AND_CHRG_CARDS',
  'LEASES',
  'MARGIN_LOANS',
  'OVERDRAFTS',
  'PERS_LOANS',
  'REGULATED_TRUST_ACCOUNTS',
  'RESIDENTIAL_MORTGAGES',
  'TERM_DEPOSITS',
  'TRADE_FINANCE',
  'TRANS_AND_SAVINGS_ACCOUNTS',
  'TRAVEL_CARDS',
];

export const FEATURE_TYPE = {
  ADDITIONAL_CARDS: 'ADDITIONAL_CARDS',
  BALANCE_TRANSFERS: 'BALANCE_TRANSFERS',
  BILL_PAYMENT: 'BILL_PAYMENT',
  BONUS_REWARDS: 'BONUS_REWARDS',
  CARD_ACCESS: 'CARD_ACCESS',
  COMPLEMENTARY_PRODUCT_DISCOUNTS: 'COMPLEMENTARY_PRODUCT_DISCOUNTS',
  DIGITAL_BANKING: 'DIGITAL_BANKING',
  DIGITAL_WALLET: 'DIGITAL_WALLET',
  DONATE_INTEREST: 'DONATE_INTEREST',
  FREE_TXNS: 'FREE_TXNS',
  FREE_TXNS_ALLOWANCE: 'FREE_TXNS_ALLOWANCE',
  INSURANCE: 'INSURANCE',
  INTEREST_FREE: 'INTEREST_FREE',
  INTEREST_FREE_TRANSFERS: 'INTEREST_FREE_TRANSFERS',
  LOYALTY_PROGRAM: 'LOYALTY_PROGRAM',
  NOTIFICATIONS: 'NOTIFICATIONS',
  NPP_ENABLED: 'NPP_ENABLED',
  NPP_PAYID: 'NPP_PAYID',
  OFFSET: 'OFFSET',
  OTHER: 'OTHER',
  OVERDRAFT: 'OVERDRAFT',
  REDRAW: 'REDRAW',
  UNLIMITED_TXNS: 'UNLIMITED_TXNS',
}

export const CONSTRAINT_TYPE = {
  MAX_BALANCE: 'MAX_BALANCE',
  MAX_LIMIT: 'MAX_LIMIT',
  MIN_BALANCE: 'MIN_BALANCE',
  MIN_LIMIT: 'MIN_LIMIT',
  OPENING_BALANCE: 'OPENING_BALANCE',
};

export const ELIGIBILITY_TYPE = {
  BUSINESS: 'BUSINESS',
  EMPLOYMENT_STATUS: 'EMPLOYMENT_STATUS',
  MAX_AGE: 'MAX_AGE',
  MIN_AGE: 'MIN_AGE',
  MIN_INCOME: 'MIN_INCOME',
  MIN_TURNOVER: 'MIN_TURNOVER',
  NATURAL_PERSON: 'NATURAL_PERSON',
  OTHER: 'OTHER',
  PENSION_RECIPIENT: 'PENSION_RECIPIENT',
  RESIDENCY_STATUS: 'RESIDENCY_STATUS',
  STAFF: 'STAFF',
  STUDENT: 'STUDENT',
};
