export const EFFECTIVE = {
	ALL: 'ALL',
	CURRENT: 'CURRENT',
	FUTURE: 'FUTURE'
};

export const PRODUCT_CATEGORY = {
	BUSINESS_LOANS: 'BUSINESS_LOANS',
	CRED_AND_CHRG_CARDS: 'CRED_AND_CHRG_CARDS',
	LEASES: 'LEASES',
	MARGIN_LOANS: 'MARGIN_LOANS',
	OVERDRAFTS: 'OVERDRAFTS',
	PERS_LOANS: 'PERS_LOANS',
	REGULATED_TRUST_ACCOUNTS: 'REGULATED_TRUST_ACCOUNTS',
	RESIDENTIAL_MORTGAGES: 'RESIDENTIAL_MORTGAGES',
	TERM_DEPOSITS: 'TERM_DEPOSITS',
	TRADE_FINANCE: 'TRADE_FINANCE',
	TRANS_AND_SAVINGS_ACCOUNTS: 'TRANS_AND_SAVINGS_ACCOUNTS',
	TRAVEL_CARDS: 'TRAVEL_CARDS'
};