import Joi from 'joi';
import { FEATURE_TYPE } from '../../constants/enum.js';

export const BankingProductFeature = Joi.object({
  featureType: Joi.string().required().valid(
    FEATURE_TYPE.ADDITIONAL_CARDS,
    FEATURE_TYPE.BALANCE_TRANSFERS,
    FEATURE_TYPE.BILL_PAYMENT,
    FEATURE_TYPE.BONUS_REWARDS,
    FEATURE_TYPE.CARD_ACCESS,
    FEATURE_TYPE.COMPLEMENTARY_PRODUCT_DISCOUNTS,
    FEATURE_TYPE.DIGITAL_BANKING,
    FEATURE_TYPE.DIGITAL_WALLET,
    FEATURE_TYPE.DONATE_INTEREST,
    FEATURE_TYPE.FREE_TXNS,
    FEATURE_TYPE.FREE_TXNS_ALLOWANCE,
    FEATURE_TYPE.INSURANCE,
    FEATURE_TYPE.INTEREST_FREE,
    FEATURE_TYPE.INTEREST_FREE_TRANSFERS,
    FEATURE_TYPE.LOYALTY_PROGRAM,
    FEATURE_TYPE.NOTIFICATIONS,
    FEATURE_TYPE.NPP_ENABLED,
    FEATURE_TYPE.NPP_PAYID,
    FEATURE_TYPE.OFFSET,
    FEATURE_TYPE.OTHER,
    FEATURE_TYPE.OVERDRAFT,
    FEATURE_TYPE.REDRAW,
    FEATURE_TYPE.UNLIMITED_TXNS,
  ),
  additionalValue: Joi.string().required(),
  additionalInfo: Joi.string().allow(null, ''),
  additionalInfoUri: Joi.string().uri().allow(null, ''),
});
